http:
  services:
    qbittorrent-svc:
      loadBalancer:
        servers:
          - url: http://gluetun:8080

    slskd-svc:
      loadBalancer:
        servers:
          - url: http://gluetun:5030
