# ==============================================================================
# TORRENTING MODULE - TRAEFIK SERVICES
# ==============================================================================
# Description: Traefik dynamic service definitions for the torrenting module
# Author: Matt Barham
# Created: 2026-02-13
# Modified: 2026-04-21
# Version: 1.0.1
# Host: Your Server
# ==============================================================================
# Type: Traefik Dynamic Config (services)
# Component: module: torrenting
# ==============================================================================

http:
  services:
    qbittorrent-svc:
      loadBalancer:
        servers:
          - url: http://gluetun:8080

    slskd-svc:
      loadBalancer:
        servers:
          - url: http://gluetun:5030
